server:
  port: 8082

spring:
  application:
    name: msvc-pedido

  datasource:
    url: jdbc:postgresql://localhost:5432/pedido_db
    username: postgres
    password: Redimi2one2025*
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
