spring:
  application:
    name: msvc-eureka
  config:
<<<<<<< HEAD
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}
=======
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}





>>>>>>> 4ff5422 (Refactorizacion y Perfilamiento dev/qa(aws) / desabilitado el actions de github)
