server:
  port: 8081


application:
  security:
    jwt:
      secret-key: McvbIKwPaVjhmBwFUdHDXzvfWeAZgaJ8XJr6cBsvNkPI9VUvAWw7GzFMV6ZhHsI
      expiration: 86400000
      refresh-token:
        expiration: 604800000

spring:
  application:
    name: msvc-authService
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Redimi2one2025*
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  config:
    import: optional:configserver:http://localhost:8888

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka



