name: Deploy Backend

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/msvc-authService/**'
      - 'backend/msvc-config/**'
      - 'backend/msvc-eureka/**'

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      auth: ${{ steps.filter.outputs.auth }}
      config: ${{ steps.filter.outputs.config }}
      eureka: ${{ steps.filter.outputs.eureka }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            auth:
              - 'backend/msvc-authService/**'
            config:
              - 'backend/msvc-config/**'
            eureka:
              - 'backend/msvc-eureka/**'

  build-config:
    needs: detect-changes
    if: needs.detect-changes.outputs.config == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/msvc-config/Dockerfile
          push: true
          tags: lblackdev/smartlogix-config:latest

  build-eureka:
    needs: detect-changes
    if: needs.detect-changes.outputs.eureka == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/msvc-eureka/Dockerfile
          push: true
          tags: lblackdev/smartlogix-eureka:latest

  build-auth:
    needs: detect-changes
    if: needs.detect-changes.outputs.auth == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/msvc-authService/Dockerfile
          push: true
          tags: lblackdev/smartlogix-auth:latest